<?php

$config['message_keys'] = [
  'voting_button' => [],
  'referrer_button' => [],
  'help_button' => [],
  'about_button' => [],
  'resend_sms' => [],
  'enter_otp_code' => [],
  'error_resending_otp' => [],
  'otp_has_ben_resent' => [],
  'try_again_otp' => [
    'seconds' => 'qayta sms yuborish uchun kutish vaqti',
  ],
  'start_message' => [],
  'voting_button_message' => [],
  'balance_button_message' => [
    'all_voices' => 'ovozlar soni',
    'balance' => 'joriy balans',
  ],
  'get_cash' => [],
  'share_referrer_link' => [],
  'share_referrer_link_message' => [
    'referrer_link' => 'referal manzili',
  ],
  'referrer_button_message' => [
    'ref_payment' => 'referal summasi',
    'ref' => 'referallar soni',
    'referrer_link' => 'referal manzili',
  ],
  'help_button_message' => [],
  'about_button_message' => [],
  'humans_message' => [],
  'cancel_button' => [],
  'understand_message' => [],
  'internal_error_message' => [],
  'number_previously_used_message' => [],
  'enter_captcha_message' => [],
  'wrong_captcha_message' => [],
  'captcha_number_required_message' => [],
  'wrong_otp_entered_message' => [],
  'expired_otp_message' => [],
  'otp_undefined_error_message' => [],
  'vote_success_message' => [],
  'vote_not_accepted_message' => [],
  'otp_code_number_format_required' => [],
  'over_limits_message' => [],
  'enter_payment_details_message' => [],
  'lack_balance_message' => [
    'min_payment' => 'minimal pul yechish miqdori',
  ],
  'payment_request_success_message' => [],
  'payment_waiting_message' => [],
  'payment_request_length_message' => [],
  'new_referrer_message' => [],
  'subscribed_message' => [],
  'go_to_channel_message' => [],
  'not_subscribed_alert_message' => [],
  'subscribe_message' => []
];